import Head from "next/head";
import Image from "next/image";
import Header from "./header";
import Product from "./product";
import Specs from "./specs";
import Testimonial from "./testimonial";
import Contact from "./contact";
export default function Home() {
  return (
    <div className="scroll-smooth">
      <Head>
        <title>Halu Slur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative h-fit  bg-gradient-to-r from-[#0d2a2e] via-[#110e11] to-[#110e11]">
        <Header />
        <div className="grid md:grid-cols-2 max-w-screen-xl mx-auto md:space-x-6  md:mt-32 ">
          <div className="space-y-8 relative">
            <h2 className="text-6xl  font-semibold text-white  hidden md:block">
              {" "}
              Get your first <br></br> Virtual Reality{" "}
              <span className="text-[#08f8ff] text-4xl">▪</span>
            </h2>
            <h2 className="text-5xl text-center  font-semibold text-white block md:hidden">
              {" "}
              Get your first Virtual Reality{" "}
              <span className="text-[#08f8ff] text-4xl">▪</span>
            </h2>
            <p className=" text-[#8d9396] text-center block md:hidden px-4">
              {" "}
              Our Product is the most innovatives VR kit and first product that
              exist.
            </p>
            <p className=" text-[#8d9396] hidden md:block">
              {" "}
              Our Product is the most innovative<br></br> VR kit and first
              product that exist.
            </p>
            <ul className="leading-tight hidden md:block">
              <ul className="flex pt-4">
                <li className="w-40 h-40 bg-[#110e11] border border-[#1c1a1d]">
                  <span className="bg-[#675aec]  px-10 py-4  text-white font-medium  text-xl">
                    {" "}
                    Buy now
                  </span>{" "}
                </li>
              </ul>
              <ul className="flex">
                <li className="w-40 h-40 bg-[#110e11] border border-[#1c1a1d] ">
                  <Image
                    className=""
                    src="/hulu(12).jpg"
                    alt="logo"
                    width={160}
                    height={160}
                  />
                </li>
              </ul>
              <ul className="flex  text-white relative items-center">
                <li className="w-40 pt-12  px-2 h-40 text-2xl bg-[#110e11] border border-[#1c1a1d] ">
                  2810
                  <p className=" text-lg text-[#a29fa3]"> Product sold</p>
                </li>
                <li className="w-40 h-40 pt-12 px-2 text-2xl bg-[#110e11] border border-[#1c1a1d] ">
                  1705
                  <p className=" text-lg text-[#a29fa3]"> Games Provided</p>
                </li>
                <li className="w-40 h-40 pt-12 px-2  text-2xl bg-[#110e11] border border-[#1c1a1d] ">
                  6<p className=" text-lg text-[#a29fa3]"> languages</p>
                </li>
              </ul>
            </ul>
          </div>
          <div  className="pt-6 md:pt-0 scroll-smooth px-4">
            <a href="#scroll" className="scroll-smooth">

            <Image
              className=""
              src="/hulu(13).jpg"
              alt="logo"
              width={650}
              height={770}
            />
            </a>
          </div>
        </div>
      </div>
      <Product />
      <Specs />
      <Testimonial />
      <Contact />
    </div>
  );
}
